# Generated by Django 5.2 on 2025-04-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=10)),
                ('time', models.CharField(max_length=50)),
                ('activity', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
